### ISSUE TITLE
Meilenstein 2 SA UND SA 

### ISSUE THREAD

**Issue by pouahang** [rodchenk/foliage#11]
Meilenstein 2 
[Meilenstein 2 SA UND SA.docx](https://github.com/rodchenk/foliage/files/2619828/Meilenstein.2.SA.UND.SA.docx)
[Meilenstein 2 SA UND SA.docx](https://github.com/rodchenk/foliage/files/2619834/Meilenstein.2.SA.UND.SA.docx)

**Comment by nickinko** [comment]
[SSAd11, ard31.docx](https://github.com/rodchenk/foliage/files/2619938/SSAd11.ard31.docx)
[SSAD_22_&_ARD_33__Ivachshenko.docx](https://github.com/rodchenk/foliage/files/2619939/SSAD_22_._ARD_33__Ivachshenko.docx)
[SSAD_23_&_ARD_12_Biggymat.docx](https://github.com/rodchenk/foliage/files/2619940/SSAD_23_._ARD_12_Biggymat.docx)
