### ISSUE TITLE
Präsentation und Ausarbeitung 

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/foliage#14]
Wir müssen bis Sonntag den 02.12.2018 die Ausarbeitung fertig machen. Jeder muss ihm/ihr zugeordnete Specific Practices zu ARD und SSAD noch mal bearbeiten und im Bezug auf unser Projekt umschreiben. 

**Zur Kenntnisnahme:**
Das Thema ist "Microservice Architektur"
Die These ist "Umbau einer monolithischer Anwendung in Microservices und Deployment im Cloud"

Das alles heißt, in unserem Projekt suchen wir nach Cloud-Anbietern basierend auf die in ARD erfassten Anforderungen. Die detaillierte Zusammenfassung von Cloud-Anbietern findet ihr [hier](https://rodchenk.github.io/foliage/#auavid-ssad-content) unter SSAD SP 1.1. 
Ich bitte euch alle möglichst früh damit anzufangen und fertig zu machen, damit wir es alles in Ruhe zusammenfassen können.  In jedem Teil minimal Theorie schreiben, sondern das praktische Vorgehen und mit Beschreibung wie und warum ihr dazu gekommen seid. 

Noch mal ihre Themen. Ich habe mir noch SSAD SP 1.2 geschnappt. Nicht vergessen, dass ARD vor SSAD kommt!

**ARD**

- SP 1.2 Develop and Prioritize Customer Requirements -> @biggymat 
- SP 3.1 Establish Operational Concepts and Scenarios -> @rodchenk 
- SP 3.3 Analyze Requirements to Achieve Balance -> @NickIvachshenko 
- SP 3.4 Validate Requirements -> @pouahang 

**SSAD**

- SP 1.1 Identify Potential Suppliers -> @rodchenk 
- SP 1.2 Establish a Solicitation Package -> @rodchenk 
- SP 2.2 Establish Negotiation Plans -> @NickIvachshenko 
- SP 2.3 Select Suppliers -> @biggymat 
- SP 3.2 Establish Supplier Agreement -> @pouahang 

Wenn alles fertig ist, müssen wir #12  machen. Am Dienstag müssen wir 15 min Vertrag halten, ich würde die Präsentation erstellen, das kann ich aber erst, wenn alles fertig ist. 

Bitte versucht eure SP bis Freitag 23:59 zu schaffen.

**Comment by rodchenk** [comment]
@biggymat hier ist die ARD SP 1.1, welches vor deiner ARD SP 1.2 kommt. Du kannst dein Teil basierend auf ARD 1.1 korrigieren und mehr Praktische Teile rein bringen.
_______________________________________________________________________________________________________________

**Elicit Stakeholder Needs**

Die Nutzung von Cloud-Diensten bringt eine Menge von Vorteilen. Wir wollen sie alle möglichst effizient und produktiv ausnutzen um hoche Qualität unserer Anwendung erreichen zu können. Wir unterscheiden die Kundenanforderungen in 3 Ebenen. 

-  **Anwendungs- und Benutzerebene**. In erster Linie steht die client-seitige Anwendung, die von den Mitarbeitern benutzt wird. Sie muss über einem geeigneten Niveau an Benutzerfreundlichkeit verfügen (Metriken zu Effektivität, Effizienz, Zufriedenheit). Messungen werden quantitativ anhand von Beobachtungen an Benutzern durchgeführt. Außerdem muss das System den internationalen Standards entsprechen, z.B. nach EN ISO 9241-110 "Grundlagen der Dialoggestaltung". 
	Es muss möglich sein, das System in mehrere unabhängige Umgebungen (Entwicklungs-, Test- und Deploymentumgebung) aufzuteilen. Die Aufteilung muss entweder durch Separation von Hardware erfolgen oder durch entsprechende Software. Die Wartung und Instandhaltung von genannten Umgebungen muss mit dem gleichen Verfahren geschehen, d.h. die Umgebungen müssen sich nur in Anwendungsszenarien unterscheiden und nicht in Bedienung. 
	Die Voraussetzung für die weitere Entwicklung unserer Anwendung sind die IDEs (Eclipse und/oder IntellijIdea für Java-Entwicklung mit etabliertem Framework Spring und Anwendungsserver JBoss), Anwendung für die Administration und Gestaltung von SQL(MySQL) und NoSQL(MongoDB) Datenbanken z.B. Intellij Datagrip oder Plug In für Eclipse, Tools für die Entwicklung von grafischer Oberfläche (Adobe Photoshop ab CS6 und Adobe Illustrator). 
	Für die interne und externe Kommunikation werden E-Mail-Server und Nachrichtendienst wie Discord oder Slack. 
	Das System muss nicht unbedingt über all diese Anwendungen verfügen, sondern es muss die Installation und Wartung dessen unterstützen. 
	

-  **Administrationsebene**. Wir erwarten vom System die Möglichkeit, jedem Teammitglied eine entsprechende Rolle zuordnen zu können. Mit dieser Rolle würde man die Autorisierungsrechte bekommen und nur auf die für ihn zugelassenen Ressourcen zugreifen können. Es wird vorausgesetzt, dass das System alle internen Änderungen im Log speichert. Dazu gehören alle Log in und Log out, geänderte Einstellungen im System und einzelnen Anwendungen sowie die Änderungen an Dateien und Ressourcen. Das System muss rund um die Uhr und von überall verfügbar sein, das heißt dass das Uptime und Response Time eine führende Rolle spielen.  

-  **Analytische Ebene**. Dazu gehören in erster Linie die etablierten Überwachungs- und Monitoringstools. Es muss möglich sein, den Status des Systems jederzeit zu prüfen. Dazu zählt das Traffic, Verwendung von physischen Ressourcen und die statistischen Daten über einen gegebenen Zeitraum. Es wird benötigt, eine Liste von allen angemeldeten Benutzern dargestellt zu bekommen.

**Comment by rodchenk** [comment]
[Hier ist die Tabelle von potentiellen Lieferanten](https://docs.google.com/spreadsheets/d/1yTpt7gmd_6Ie0BxBK9Zlu3xwKSV9ubfBx-eeYGPMAlk/edit?usp=sharing) aus SSAD SP 1.1
Die aktuelle Ausarbeitung findet ihr unter [diesem Link](https://docs.google.com/document/d/17ig-EgtklvQFj6OZ3ApGG8uozpS6PH70oltDxp0KnZw/edit?usp=sharing).
![no](https://2.bp.blogspot.com/-2aOuLmYHBeE/VRujJJ76MLI/AAAAAAAAD3g/cW2Km1btkeM/s1600/i%2Bunderstand%2Bnothing.jpg)

**Comment by rodchenk** [comment]
Die aktuelle Ausarbeitung findet ihr unter [diesem Link](https://docs.google.com/document/d/17ig-EgtklvQFj6OZ3ApGG8uozpS6PH70oltDxp0KnZw/edit?usp=sharing).

**Comment by rodchenk** [comment]
**10 std 8 min** bis zum Deadline

**Comment by pouahang** [comment]
[SSAD  und ARD Ausarbeitung.pdf](https://github.com/rodchenk/foliage/files/2636339/SSAD.und.ARD.Ausarbeitung.pdf)

**Comment by pouahang** [comment]
Hallo Leute, ich habe die eure Ausarbeitung gesehen aber ich kann nicht meine Teile hinzufügen. Könnt ihr mir bitte dabei helfen?
Danke

**Comment by rodchenk** [comment]
@biggymat ich füge dein altes Teil in die Ausarbeitung hinzu, wir müssen schon abgeben

**Comment by rodchenk** [comment]
[Ausarbeitung ARD SSAD AHP.pdf](https://github.com/rodchenk/foliage/files/2637088/Ausarbeitung.ARD.2FSSAD.2FAHP.pdf)
 @pouahang  @NickIvachshenko  @biggymat  @rodchenk 
enjoy

**Comment by rodchenk** [comment]
[presentation.pdf](https://github.com/rodchenk/foliage/files/2643659/presentation_4.12.pdf)
