### ISSUE TITLE
BPMN modellieren 

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/foliage#15]
Habt ihr Vorschläge was wir überhaupt da modellieren können?

**Comment by rodchenk** [comment]
![BPMN](https://vignette.wikia.nocookie.net/battlefordreamisland/images/7/7a/ForeverAlone.jpg/revision/latest?cb=20180203114507)

**Comment by rodchenk** [comment]
Ich übernehme dieses Teil, hab schon angefangen

**Comment by nickinko** [comment]
Prozess:  Neue Funktionalität in da System/Plattform zu entwickeln.
###
Daten:
---
Einflussgrößen:
1.	Team und Qualifikation (Personen und Fachwissen)
2.	Gesamtkosten 		(xxx bis xxx €)
3.	Zeit für die Entwicklung (yyy bis yyy Tagen/Stunden/Monaten) (?)
---
Regelmuster:
1.	Zeit und Kosten sind umgekehrt proportional (je mehr Kosten – desto grösser die Zeit und umgekehrt)
2.	Qualifikation der Mitarbeiter kann die Entwicklungszeit verringern, aber die Kosten werden höher.
3.	Projekt kann man initiieren nur mit minimale ausreichende Anzahl von Personen im Team (von 3 bis 9 Personen)
---
Ausgabewerten:
1.	Möglichkeit der Projektumsetzung in Prozentsatz
0-33%		- sinnlos
34-66%		- problematisch
67-100%	- realisierbar
---
. . .

**Comment by nickinko** [comment]
![bpmnprozess_alphaversion](https://user-images.githubusercontent.com/32674066/50134577-ead6c280-0290-11e9-9f17-f0df1da69a7e.png)
---
[BPMNP_File_here.zip](https://github.com/rodchenk/foliage/files/2689047/BPMNP_File_here.zip)

**Comment by nickinko** [comment]
![diagram_2 1](https://user-images.githubusercontent.com/32674066/50725540-38f81c80-10ff-11e9-8282-28ee1cdfc206.png)
[diagram_2.1.zip](https://github.com/rodchenk/foliage/files/2729588/diagram_2.1.zip)

**Comment by nickinko** [comment]
Prozess: Manuelle Lösung des Problems bei Erkennung im automatischen Überwachungssystem

**Comment by NickIvachshenko** [comment]
![dmn](https://user-images.githubusercontent.com/32674066/50800467-a616d800-12e0-11e9-8aa1-3f24db213f88.jpg)
***
DMN Skizze

**Comment by rodchenk** [comment]
BPM ist in Repo [/foliage-apartments-bpmn](https://github.com/rodchenk/foliage-apartments-bpmn) zu finden.
