### ISSUE TITLE
Datenschutz: Wie können Anbieter via Facebook Informationen von Nutzer sehen

### ISSUE THREAD

**Issue by pouahang** [rodchenk/foliage#16]
[Login per Facebook für andere Webseite.pdf](https://github.com/rodchenk/foliage/files/2673641/Login.per.Facebook.fur.andere.Webseite.pdf)

Ehrlich zu sagen könnte ich nicht richtig diese Frage von Herr Keller antworten . Guckt ihr bitte das an und sagt mir bitte , was ihr daran denkt. Und wenn ihr eine bessere Antwort gefunden habt bitte lädt es hoch damit ich auch lesen kann. 
Bis morgen

**Comment by rodchenk** [comment]
### Präsentation
[Datenschutz facebook Oauth2](https://github.com/rodchenk/foliage/files/2675974/datenschutz_facebook.pdf)
ich hab das erstellt, aber sieht so aus, als würden wir es heute nicht präsentieren können.
Ich habe eine Bitte an euch, wir müssen uns sehr gut für die nächste Woche vorbereiten und eine 30-min lange Präsentation machen, mit cooler Info, Bildern. Nicht 5 min im Internet suchen, sondern gut vorbereiten, auswendig lernen usw. Ansonsten wird es sehr **gefährlich**.

**Comment by pouahang** [comment]
Wenn ihr nur 5 min im Internet sucht, ich nicht. Alles was ich erstelle kostet mir sehr viel Zeit und ich mache immer meine beste, um die richtige Informationen zu finden. Wenn ihr auch an der Frage gearbeitet habt, kannst du nur versuchen die wichtige Details zu suzammenfassen und eine kleine präsention zu erstellen. 
Du hast recht wenn wir heute nicht machen wird es sehr kritisch für uns egal ob wir nächte Woche 30 min oder 1 Stunde Präsentation machen. Ich kann nächste Woche präsentiert wenn ihr wollt aber heute bin ich wirklich eingeschränkt. Bitte zeigt ihm nur einfach , was wir für die Frage gefunden haben, weil er uns  das seit langer zeit fragt. Wenn es nicht stimmt wird er uns ein bisschen orientiert. Wichtig ist dass er merkt, dass wir recherchiert haben.

**Comment by pouahang** [comment]
Hallo Leute,
habt ihr bitte eine Idee was wir für Datenschutz vorbereiten können?
