### ISSUE TITLE
Projektvorstellung Datenschutz

### ISSUE THREAD

**Issue by pouahang** [rodchenk/foliage#7]
Hauptpunkte:
- Produkt
- nutzen
- Konkurenz
- Rechtlichen Rahmen
          
    Forschungsfragen:

- Wie kann ich eine webseite besuchen ohne aktiv oder angemeldet zu sein?
- "EDC Edit Trend website"
- welche prozesse der Zertifizierung gibt es ?
- welche probleme der Authorisierungsmodule gibt es ?

Ich habe mir einen Schlüßel vom Labor 321 besorgt. Wir ihr Zeit am Wochenende habt, können wir an unseren Projekten arbeiten.

**Comment by rodchenk** [comment]
Wann müssen wir es vortragen? die Forschungsfragen beziehen sich auf unser Projekt oder auf alle?

**Comment by pouahang** [comment]
bis über nächste Woche, und nächste Woche gibt es keine Vorlesung. Die Forschungsfragen beziehen sich auf alle .
