### ISSUE TITLE
SSAD und ARD Themen

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/foliage#8]
[CMMI Prozessgebiete](https://moodle.th-brandenburg.de/course/view.php?id=5227#section-4)
Fur unser Projekt sind folgende [Themen](https://moodle.th-brandenburg.de/mod/resource/view.php?id=267358) relevant:
**SSAD**

- SP 1.1 Identify Potential Suppliers -> @rodchenk 
- SP 2.2 Establish Negotiation Plans -> @NickIvachshenko 
- SP 2.3 Select Suppliers -> @biggymat 
- SP 3.2 Establish Supplier Agreement -> @pouahang 

**ARD**

- SP 1.2 Develop and Prioritize Customer Requirements -> @biggymat 
- SP 3.1 Establish Operational Concepts and Scenarios -> @rodchenk 
- SP 3.3 Analyze Requirements to Achieve Balance -> @NickIvachshenko 
- SP 3.4 Validate Requirements -> @pouahang

**Comment by rodchenk** [comment]
Abgabetermin **2.12.2018**

**Comment by rodchenk** [comment]
Recherchieren und kurze Ausarbeitung schreiben. Danach hier posten und ich stecke das in die Webseite rein.

**Comment by pouahang** [comment]
alles klar

**Comment by biggymat** [comment]
jungs treffen wir uns dann am WE?

**Comment by rodchenk** [comment]
> jungs treffen wir uns dann am WE?

ja, das passt mir. wie sieht es bei den anderen aus?

**Comment by pouahang** [comment]
das passt mir auch aber ab 13 Uhr bitte

**Comment by nickinko** [comment]
[SSAD_22_&_ARD_33__Ivachshenko.pdf](https://github.com/rodchenk/foliage/files/2612600/SSAD_22_._ARD_33__Ivachshenko.pdf)

**Comment by biggymat** [comment]
[Auswahl der IT.pdf](https://github.com/rodchenk/foliage/files/2618757/Auswahl.der.IT.pdf)
