### ISSUE TITLE
Einträge für Datenschutz

### ISSUE THREAD

**Issue by rodchenk** [rodchenk/foliage#9]

**Comment by rodchenk** [comment]
**Produkt:**
Wir entwickeln ein projekt-, aktiviatäts- und zeitmanagementorientiertes soziales Netzwerk, das eine Alternative zum klassischen Ticketsystem (z. B. JIRA) darstellt. Es orientiert sich vor allem auf die jungen engagierten Menschen und nicht auf die Unternehmen. Da wir eine hohe Zahl von Benutzern erwarten, stellt sich die Frage, wie die Datensicherheit und der Datenschutz im Unternehmen bzw. im Netz gestaltet werden sollte. Darüber hinaus hat das deutsche/europäische Gesetz eigene Anforderungen, was die sozialen Netze betrifft.

**Comment by rodchenk** [comment]
**Architekturkonzept:**
Die alte Architektur von unserer Web-Applikation hat nur über einen einzigen Eingang ins System verfügt. Das heißt, bei jeder Anfrage wurde geprüft, ob der Benutzer autorisiert ist, falls nicht → wird der Benutzer auf Login-Seite redirected. Login bzw. Regisitrierungsteil war monolithisch mit der Applikation verbunden und könnte nicht wiederverwendet werden. In dem aktuellen Architekturkonzept haben wir besorgt, dass Security-Verfahren möglichst flexibel gestalten ist, sodass es mehrmals für verschiedene Zwecke verwendet werden könnte. Beispielweise möchten wir es ermöglichen, sich an externen Web-Applikation über unseren Security-Modul authentifizieren zu können (OAuth2, siehe unten). Für hohe Flexibilität wurden alle Security-bezogenen Zeuge in ein externes Modul ausgelagert. Die Kommunikation zwischen Security-Modul und der restlichen Logik findet über eine Schnittstelle statt. Dieser Betrachtungsweise ermöglicht die Verteilung von Aufgaben und Verantwortlichkeiten innerhalb von Entwicklerteam. Darüber hinaus haben wir den Code für Security Modul von PHP auf Java mit Spring Security umgeschrieben. Dies bietet unterschiedliche Designmuster und Konzepte für ein sicheres und zuverlässiges Security-verfahren an. Das Verschlüsseln von Passwörtern erfolgt mit bcrypt Algorithmus. Die restliche Logik ist ebenso auf Java Spring umgeschrieben und dies verfügt über eine REST API Schnittstelle, d. h. jeder Ressource ist mit seinem Bezeichner zu finden. Das ermöglicht mehrere Eingänge ins System, aber diesmal ist nicht die Authentifizierung zu prüfen, sondern die Zugriffsrechte/ Autorisierungsrechte. Die Zugriffsrechte in unserem System sind in 8 Schnitte aufgeteilt (von 0 bis 7). Der nicht angemeldete Benutzer hat die Zugriffsrechte 0, das heißt, er darf nur die Seiten angucken, die das Permission weniger als 1 haben, z.B. Login-/Registrierungsseite, Nichtprivate Accounts und Projekte von anderen Benutzern usw. Benutzer mit Zugriffsrechten 5 und 6 können die anderen Benutzer sperren/entsperren und die Einträge editieren/löschen. Die Benutzer mit den höchsten Zugriffsrechten 7 (Admin) verfügen über einen Gott-Modus im System. Die Authentifizierung mit Zugriffsrechten > 5 (interne Mitarbeiter) erfolgt über Zwei-Faktor-Authentisierung (2FA).

**Comment by rodchenk** [comment]
wenn ihr Zeit habt, schnappt euch bitte die anderen zwei Punkte OAuth und Rechtlich Anforderungen @NickIvachshenko  @pouahang . Ich habe unsere Seite aktualisiert, schaut bitte mal rein.

**Comment by pouahang** [comment]
Sehr gut beschrieben .

**Comment by nickinko** [comment]
**OAuth 2** ist ein Autorisierungsframework, mit dem eingeschränkten Zugriff auf Benutzerkonten in HTTP-Diensten gewährleistet wird. OAuth funktioniert auf originales Protokoll und unterstütz Web-, sowie Desktop- bzw. Mobile Applikationen.

**Systemhierarchie und Konzept:**

**Kontoinhaber: Benutzer**
Der Benutzer autorisiert sein Konto. Der Zugriff einen Dienst auf dem Benutzerkonto ist beschränkt (lesende- oder schreibende Zugriff).

**Ressourcenserver und Autorisierungsserver: API**
Der Ressourcenserver speichert die geschützten Daten von Benutzerkonten und der Autorisierungsserver verifiziert die Authentizität der vom Benutzer bereitgestellten Informationen und erstellt dann Autorisierungstoken für die Anwendung, über die die Anwendung auf Benutzerdaten realisiert wird. 
Aus Sicht des Anwendungsentwicklers führt die Service-API sowohl die Ressourcenserverrolle als auch die Autorisierungsserverrolle aus.

**Client: externer Service** 
Applikation bzw. Dienst, die auf das Benutzerkonto zugreifen, muss vor dem Zugriff vom Benutzer autorisiert werden und die Autorisierung muss von der API kontrolliert werden.

**Comment by pouahang** [comment]
Anmerkungen der von 01.11.18 Präsentation
- Wie kann man der Profil von Handeln lesen?(Wenn man sich mit Facebook anmelden)
- Wie kann man das System im Unternehmen umsetzen.

**Comment by pouahang** [comment]
Die nächste Präsentation findet am 08.11.18 statt. leider könnte ich nicht da sein.
Da ihr gut das Thema kennt, sag mir bescheid welche Punkte ich bearbeiten soll.
Ich werde die PowerPont Datei für die Präsentation erstellen. Es wäre schön , wenn wir spätesten am Dientag damit fertig seien, sodass derjeniger , der präsentieren wil sich vorbereiten. Ich werde die übernächste Präsentation übernehmen.

**Comment by nickinko** [comment]
wie Konnen sich  Kunden fu einen anderen Handler(Plattform) identifizieren lassen?

**Comment by rodchenk** [comment]
### deprecated
